# Generated by Django 2.2.12 on 2020-10-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletics_league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteranking',
            name='AgeGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='athletics_league.AgeGroup'),
        ),
    ]
