# Generated by Django 2.2.12 on 2020-10-18 16:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('athletics_league', '0002_athleteranking_agegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='Coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='athletics_league.Coach'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='Coach_ID',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular Coach across whole league', primary_key=True, serialize=False),
        ),
    ]
