# Generated by Django 2.2.12 on 2020-10-30 18:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('athletics_league', '0003_auto_20201018_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthletePB',
            fields=[
                ('AthletePB_ID', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular Personal Best', primary_key=True, serialize=False)),
                ('PB', models.CharField(max_length=20)),
                ('AgeGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='athletics_league.AgeGroup')),
                ('Athlete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='athletics_league.Athlete')),
                ('Season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='athletics_league.Season')),
                ('Speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='athletics_league.Speciality')),
            ],
        ),
    ]
