# Generated by Django 2.2.12 on 2020-10-31 10:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('athletics_league', '0004_athletepb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('Gender_ID', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular Gender', primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Felmale')], default='M', help_text='Athlete Gender', max_length=1000000)),
            ],
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='status',
        ),
        migrations.AlterField(
            model_name='season',
            name='season_year',
            field=models.CharField(blank=True, choices=[('15/16', '2015/2016'), ('16/17', '2016/2017'), ('17/18', '2017/2018'), ('18/19', '2018/2019'), ('19/20', '2019/2020'), ('20/21', '2020/2021'), ('21/22', '2021/2022'), ('ALL', 'ALL')], default='15/16', help_text='Season', max_length=10000000),
        ),
        migrations.AddField(
            model_name='athlete',
            name='Athlete_Gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='athletics_league.Gender'),
        ),
        migrations.AddField(
            model_name='athletepb',
            name='Gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='athletics_league.Gender'),
        ),
    ]
