# Generated by Django 2.2.12 on 2020-10-31 10:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('athletics_league', '0005_auto_20201031_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialityType',
            fields=[
                ('SpecialityType_ID', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular Speciality across whole league', primary_key=True, serialize=False)),
                ('Speciality_type', models.CharField(blank=True, choices=[('T', 'Track'), ('F', 'Field')], default='T', help_text='speciality type', max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='speciality',
            name='Speciality_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='athletics_league.SpecialityType'),
        ),
    ]
