# Generated by Django 2.2.12 on 2020-10-31 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletics_league', '0007_auto_20201031_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletepb',
            name='PB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='athletics_league.TrackEventResult'),
        ),
    ]
