# Generated by Django 2.2.12 on 2020-11-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletics_league', '0008_auto_20201031_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletepb',
            name='PB_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
