# Generated by Django 2.2.12 on 2020-11-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletics_league', '0009_athletepb_pb_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletepb',
            name='pb_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
