# Generated by Django 2.2.12 on 2020-11-08 17:34

from django.db import migrations, models
import django.utils.timezone
from datetime import timedelta

class Migration(migrations.Migration):

    dependencies = [
        ('athletics_league', '0010_athletepb_pb_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackeventresult',
            name='duration',
            field=models.DurationField(default=timedelta(minutes=20)),
            preserve_default=False,
        ),
    ]
