# Generated by Django 2.2.12 on 2020-11-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletics_league', '0011_trackeventresult_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
