# Generated by Django 2.2.12 on 2020-11-14 18:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('athletics_league', '0012_event_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRound',
            fields=[
                ('eventRound_ID', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular event round', primary_key=True, serialize=False)),
                ('event_round', models.CharField(blank=True, choices=[('Heat', 'Heat'), ('Semi-final', 'Semi-final'), ('Final', 'Final')], default='Heat', help_text='Round Type', max_length=10000000)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='round_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='athletics_league.EventRound'),
        ),
    ]
