# Generated by Django 3.0.8 on 2020-11-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletics_league', '0016_trackeventresult_round_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackeventresult',
            name='round_type',
        ),
    ]
